import { useEffect, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import CodeMirror from '@uiw/react-codemirror';
import { markdown } from '@codemirror/lang-markdown';
import { oneDark } from '@codemirror/theme-one-dark';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import rehypeSanitize from 'rehype-sanitize';
import type { Dashboard, Note, Project, PromptCategory, PromptTemplate, Tag, WeeklyReport } from '../../shared/types';
import { EmptyState } from '../components/EmptyState';
import { shortDate } from '../lib/date';
import { TaskList } from './TasksPage';

export function DashboardPage() {
  const navigate = useNavigate(); const [data, setData] = useState<Dashboard | null>(null);
  useEffect(() => { void window.workbench.dashboard.get().then(setData); }, []);
  if (!data) return <div className="loading">正在打开今日总览…</div>;
  return <div className="page dashboard"><section className="welcome"><div><p className="eyebrow">{new Intl.DateTimeFormat('zh-CN', { weekday: 'long', month: 'long', day: 'numeric' }).format(new Date())}</p><h1>把今天过得清晰一点。</h1></div><div className="week-focus"><span>本周专注</span><strong>{(data.weekFocusSeconds / 3600).toFixed(1)} h</strong></div></section><div className="metric-grid"><Metric label="今日待办" value={data.todayTasks.length} tone="blue" /><Metric label="逾期任务" value={data.overdueTasks.length} tone="red" /><Metric label="最近笔记" value={data.recentNotes.length} tone="purple" /><Metric label="常用模板" value={data.favoritePrompts.length} tone="green" /></div><section className="two-columns"><Panel title="今日待办" action="查看全部" onAction={() => navigate('/tasks')}><TaskList tasks={data.todayTasks} onEdit={() => navigate('/tasks')} onComplete={async (task) => { await window.workbench.tasks.complete(task.id); setData(await window.workbench.dashboard.get()); }} /></Panel><Panel title="逾期任务" action="处理任务" onAction={() => navigate('/tasks')}><TaskList tasks={data.overdueTasks} onEdit={() => navigate('/tasks')} onComplete={async (task) => { await window.workbench.tasks.complete(task.id); setData(await window.workbench.dashboard.get()); }} /></Panel></section></div>;
}

export function NotesPage() {
  const [params, setParams] = useSearchParams(); const [notes, setNotes] = useState<Note[]>([]); const [selected, setSelected] = useState<Note | null>(null); const [search, setSearch] = useState(''); const [preview, setPreview] = useState(false);
  const refresh = () => window.workbench.notes.list(search).then((rows) => { setNotes(rows); if (selected?.id) setSelected(rows.find((note) => note.id === selected.id) || null); });
  useEffect(() => { void refresh(); }, [search]); useEffect(() => { if (params.get('new') === '1') { create(); setParams({}, { replace: true }); } }, [params, setParams]);
  const create = () => { setPreview(false); setSelected({ id: '', title: '未命名笔记', content: '', projectId: null, tags: [], createdAt: '', updatedAt: '' }); };
  const save = async () => { if (!selected) return; const result = await window.workbench.notes.save({ id: selected.id || undefined, title: selected.title, content: selected.content }); setSelected(result); await refresh(); };
  const remove = async () => { if (selected?.id && window.confirm(`删除笔记“${selected.title}”？`)) { await window.workbench.notes.remove(selected.id); setSelected(null); await refresh(); } };
  const attach = async () => { if (!selected?.id) return; const link = await window.workbench.notes.attach(selected.id); if (link) setSelected({ ...selected, content: `${selected.content}\n\n[附件](${link})` }); };
  return <div className="page notes-page"><aside className="notes-list"><div className="page-tools"><input className="search" placeholder="搜索笔记…" value={search} onChange={(event) => setSearch(event.target.value)} /><button className="primary icon-button" onClick={create}>＋</button></div>{notes.map((note) => <button className={`note-item ${selected?.id === note.id ? 'selected' : ''}`} key={note.id} onClick={() => { setPreview(false); setSelected(note); }}><strong>{note.title}</strong><small>{shortDate(note.updatedAt)} · {note.content.slice(0, 42) || '空白笔记'}</small></button>)}</aside><section className="editor-panel">{selected ? <><div className="editor-toolbar"><input className="note-title" value={selected.title} onChange={(event) => setSelected({ ...selected, title: event.target.value })} /><div><button className="quiet" onClick={() => setPreview(!preview)}>{preview ? '编辑' : '预览'}</button><button className="quiet" onClick={attach} disabled={!selected.id}>附件</button><button className="danger compact-danger" onClick={() => void remove()} disabled={!selected.id}>删除</button><button className="primary" onClick={() => void save()}>保存</button></div></div>{preview ? <article className="markdown-preview"><ReactMarkdown remarkPlugins={[remarkGfm]} rehypePlugins={[rehypeSanitize]} components={{ a: ({ href, children }) => <a href={href} onClick={(event) => { if (href?.startsWith('attachment://')) { event.preventDefault(); void window.workbench.notes.openAttachment(href.slice('attachment://'.length)); } }}>{children}</a> }}>{selected.content}</ReactMarkdown></article> : <CodeMirror value={selected.content} height="100%" theme={oneDark} extensions={[markdown()]} onChange={(content) => setSelected({ ...selected, content })} />}</> : <EmptyState text="选择一条笔记，或新建一条速记。" />}</section></div>;
}

export function PromptsPage() {
  const [items, setItems] = useState<PromptTemplate[]>([]); const [selected, setSelected] = useState<PromptTemplate | null>(null); const [search, setSearch] = useState(''); const [categories, setCategories] = useState<PromptCategory[]>([]);
  const refresh = () => Promise.all([window.workbench.prompts.list(search), window.workbench.prompts.categories()]).then(([promptRows, categoryRows]) => { setItems(promptRows); setCategories(categoryRows); });
  useEffect(() => { void refresh(); }, [search]); const create = () => setSelected({ id: '', title: '未命名模板', body: '', categoryId: null, tags: [], favorite: false, usageCount: 0, lastUsedAt: null, createdAt: '', updatedAt: '' });
  const save = async () => { if (!selected) return; setSelected(await window.workbench.prompts.save({ id: selected.id || undefined, title: selected.title, body: selected.body, categoryId: selected.categoryId, favorite: selected.favorite })); await refresh(); };
  const use = async () => { if (!selected) return; const names = [...new Set([...selected.body.matchAll(/{{\s*([\w.-]+)\s*}}/g)].map((match) => match[1]))]; const values: Record<string, string> = {}; names.forEach((name) => { values[name] = window.prompt(`填写变量：${name}`, '') || ''; }); await window.workbench.prompts.use(selected.id, values); window.alert(names.length ? '已填充变量并复制。' : '模板已复制。'); await refresh(); };
  const remove = async () => { if (selected?.id && window.confirm(`删除模板“${selected.title}”？`)) { await window.workbench.prompts.remove(selected.id); setSelected(null); await refresh(); } };
  return <div className="page prompts-page"><aside className="notes-list"><div className="page-tools"><input className="search" placeholder="搜索模板…" value={search} onChange={(event) => setSearch(event.target.value)} /><button className="primary icon-button" onClick={create}>＋</button></div>{items.map((item) => <button className={`note-item ${selected?.id === item.id ? 'selected' : ''}`} key={item.id} onClick={() => setSelected(item)}><strong>{item.favorite ? '★ ' : ''}{item.title}</strong><small>{item.categoryName || '未分类'} · 使用 {item.usageCount} 次</small></button>)}</aside><section className="editor-panel">{selected ? <><div className="editor-toolbar"><input className="note-title" value={selected.title} onChange={(event) => setSelected({ ...selected, title: event.target.value })} /><div><button className="danger compact-danger" disabled={!selected.id} onClick={() => void remove()}>删除</button><button className="quiet" onClick={() => void save()}>保存</button><button className="primary" disabled={!selected.id} onClick={() => void use()}>复制使用</button></div></div><label className="category-select">分类<select value={selected.categoryId || ''} onChange={(event) => setSelected({ ...selected, categoryId: event.target.value || null })}><option value="">未分类</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><CodeMirror value={selected.body} height="calc(100% - 90px)" theme={oneDark} extensions={[markdown()]} onChange={(body) => setSelected({ ...selected, body })} /></> : <EmptyState text="选择模板，或新建一个可复用的提示词。" />}</section></div>;
}

export function ReportsPage() { const [report, setReport] = useState<WeeklyReport | null>(null); const [message, setMessage] = useState(''); useEffect(() => { void window.workbench.reports.weekly().then(setReport); }, []); if (!report) return <div className="loading">正在生成周报…</div>; return <div className="page report"><div className="page-tools"><div><p className="muted">周一至周日 · 本机时区</p><h3>本周工作周报</h3></div><div><button className="quiet" onClick={async () => { await window.workbench.reports.copy(report.markdown); setMessage('已复制 Markdown'); }}>复制 Markdown</button><button className="primary" onClick={async () => { const saved = await window.workbench.reports.saveWeekly(); if (saved) setMessage(`已保存至 ${saved}`); }}>导出 .md</button></div></div>{message && <p className="success">{message}</p>}<article className="markdown-preview report-content"><ReactMarkdown remarkPlugins={[remarkGfm]} rehypePlugins={[rehypeSanitize]}>{report.markdown}</ReactMarkdown></article></div>; }

export function SettingsPage() {
  const [projects, setProjects] = useState<Project[]>([]); const [tags, setTags] = useState<Tag[]>([]); const [name, setName] = useState(''); const [tagName, setTagName] = useState(''); const [message, setMessage] = useState('');
  const refresh = () => Promise.all([window.workbench.projects.list(), window.workbench.tags.list()]).then(([projectRows, tagRows]) => { setProjects(projectRows); setTags(tagRows); }); useEffect(() => { void refresh(); }, []);
  return <div className="page settings"><section className="settings-card"><h3>项目</h3><div className="inline-form"><input placeholder="项目名称" value={name} onChange={(event) => setName(event.target.value)} /><button className="primary" onClick={async () => { if (name.trim()) { await window.workbench.projects.save({ name, color: '#6d92e7' }); setName(''); await refresh(); } }}>添加</button></div>{projects.map((project) => <div className="management-row" key={project.id}><span style={{ background: project.color }} />{project.name}<button className="quiet" onClick={async () => { if (window.confirm(`删除项目“${project.name}”？任务不会删除。`)) { await window.workbench.projects.remove(project.id); await refresh(); } }}>删除</button></div>)}</section><section className="settings-card"><h3>标签</h3><div className="inline-form"><input placeholder="标签名称" value={tagName} onChange={(event) => setTagName(event.target.value)} /><button className="primary" onClick={async () => { if (tagName.trim()) { await window.workbench.tags.save({ name: tagName, color: '#87a9f5' }); setTagName(''); await refresh(); } }}>添加</button></div>{tags.map((tag) => <div className="management-row" key={tag.id}><span style={{ background: tag.color }} />{tag.name}<button className="quiet" onClick={async () => { await window.workbench.tags.remove(tag.id); await refresh(); }}>删除</button></div>)}</section><section className="settings-card"><h3>本地备份与恢复</h3><p>备份包含加密数据库、密钥信封与附件。</p><div><button className="primary" onClick={async () => { const file = await window.workbench.backup.export(); if (file) setMessage(`已导出：${file}`); }}>导出加密备份</button><button className="danger" onClick={() => void window.workbench.backup.restore()}>从备份恢复</button></div></section>{message && <p className="success">{message}</p>}</div>;
}

function Metric({ label, value, tone }: { label: string; value: number; tone: string }) { return <article className={`metric ${tone}`}><span>{label}</span><strong>{value}</strong></article>; }
function Panel({ title, action, onAction, children }: { title: string; action?: string; onAction?: () => void; children: React.ReactNode }) { return <section className="panel"><header><h3>{title}</h3>{action && <button className="link-button" onClick={onAction}>{action} →</button>}</header>{children}</section>; }
