import { useEffect, useState } from 'react';
import type { Habit, HabitDay, HydrationDay, HydrationSettings } from '../../shared/types';
import { Dialog } from '../components/Dialog';
import { EmptyState } from '../components/EmptyState';
import { localDay, monthKey } from '../lib/date';

export function HabitsPage() {
  const [habits, setHabits] = useState<Habit[]>([]); const [days, setDays] = useState<HabitDay[]>([]); const [hydration, setHydration] = useState<HydrationDay | null>(null); const [settings, setSettings] = useState<HydrationSettings | null>(null); const [creating, setCreating] = useState(false); const day = localDay();
  const refresh = () => Promise.all([window.workbench.habits.list(), window.workbench.habits.days(monthKey(new Date())), window.workbench.hydration.get(day), window.workbench.hydration.settings()]).then(([habitRows, dayRows, hydrationRow, settingsRow]) => { setHabits(habitRows); setDays(dayRows); setHydration(hydrationRow); setSettings(settingsRow); });
  useEffect(() => { void refresh(); }, []);
  const toggle = async (habit: Habit) => { await window.workbench.habits.toggle(habit.id, day); await refresh(); };
  return <div className="page habits-page"><section className="hydration-card"><div><p className="eyebrow">今日喝水</p><h2>{hydration ? `${hydration.amount} / ${hydration.goal} 杯` : '加载中…'}</h2><p className="muted">每次记录一杯，可在下方调整目标与提醒。</p></div><button className="primary" onClick={async () => { await window.workbench.hydration.add(1); await refresh(); }}>＋ 记录一杯</button></section><section className="habits-section"><header><div><p className="eyebrow">每日习惯</p><h3>今天完成什么？</h3></div><button className="primary" onClick={() => setCreating(true)}>＋ 新习惯</button></header>{habits.length ? <div className="habit-grid">{habits.map((habit) => { const completed = days.some((entry) => entry.habitId === habit.id && entry.day === day); return <button className={`habit-card ${completed ? 'complete' : ''}`} key={habit.id} onClick={() => void toggle(habit)}><span style={{ background: habit.color }} /> <strong>{habit.name}</strong><small>{completed ? '今天已完成' : `每周目标 ${habit.targetDays} 天`}</small><b>{completed ? '✓' : '＋'}</b></button>; })}</div> : <EmptyState text="创建一个可持续的小习惯。" />}</section>{settings && <section className="settings-card hydration-settings"><h3>喝水提醒</h3><label>每日目标（杯）<input type="number" min="1" max="30" value={settings.dailyGoal} onChange={(event) => setSettings({ ...settings, dailyGoal: Number(event.target.value) })} /></label><label>提醒间隔（分钟）<input type="number" min="15" max="480" value={settings.reminderMinutes} onChange={(event) => setSettings({ ...settings, reminderMinutes: Number(event.target.value) })} /></label><button className="quiet" onClick={async () => { await window.workbench.hydration.saveSettings(settings); await refresh(); }}>保存提醒设置</button></section>}{creating && <HabitDialog onClose={() => setCreating(false)} onSaved={async () => { setCreating(false); await refresh(); }} />}</div>;
}

function HabitDialog({ onClose, onSaved }: { onClose: () => void; onSaved: () => Promise<void> }) {
  const [name, setName] = useState(''); const [color, setColor] = useState('#74d4a5'); const [targetDays, setTargetDays] = useState(7);
  return <Dialog title="新建习惯" onClose={onClose}><form className="form-grid" onSubmit={async (event) => { event.preventDefault(); await window.workbench.habits.save({ name, color, targetDays }); await onSaved(); }}><label className="wide">习惯名称<input value={name} onChange={(event) => setName(event.target.value)} autoFocus required /></label><label>颜色<input type="color" value={color} onChange={(event) => setColor(event.target.value)} /></label><label>每周目标天数<input type="number" min="1" max="7" value={targetDays} onChange={(event) => setTargetDays(Number(event.target.value))} /></label><div className="dialog-actions wide"><button className="quiet" type="button" onClick={onClose}>取消</button><button className="primary" type="submit">创建习惯</button></div></form></Dialog>;
}
