import { useEffect, useState } from 'react';
import type { RssEntry, RssFeed } from '../../shared/types';
import { EmptyState } from '../components/EmptyState';
import { shortDate } from '../lib/date';

export function RssPage() {
  const [feeds, setFeeds] = useState<RssFeed[]>([]); const [entries, setEntries] = useState<RssEntry[]>([]); const [url, setUrl] = useState(''); const [groupName, setGroupName] = useState(''); const [search, setSearch] = useState(''); const [unreadOnly, setUnreadOnly] = useState(false); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  const refresh = async () => { const [feedRows, entryRows] = await Promise.all([window.workbench.rss.feeds(), window.workbench.rss.entries({ search, unreadOnly })]); setFeeds(feedRows); setEntries(entryRows); };
  useEffect(() => { void refresh(); }, [search, unreadOnly]);
  const add = async () => { if (!url.trim()) return; setBusy(true); setMessage(''); try { const feed = await window.workbench.rss.saveFeed({ url, groupName }); await window.workbench.rss.refresh(feed.id); setUrl(''); setGroupName(''); await refresh(); } catch (error: any) { setMessage(error.message || '无法添加订阅。'); } finally { setBusy(false); } };
  const refreshAll = async () => { setBusy(true); setMessage(''); try { await window.workbench.rss.refresh(); await refresh(); setMessage('订阅已刷新。'); } catch (error: any) { setMessage(error.message || '部分订阅刷新失败。'); } finally { setBusy(false); } };
  return <div className="page rss-page"><section className="rss-intro"><div><p className="eyebrow">RSS / ATOM</p><h2>把值得读的内容集中起来。</h2><p>仅支持 HTTPS 订阅地址；内容以安全纯文本缓存，点击标题才会在系统浏览器打开原文。</p></div><button className="primary" disabled={busy} onClick={() => void refreshAll()}>{busy ? '刷新中…' : '刷新全部'}</button></section><section className="settings-card rss-add"><h3>添加订阅</h3><div className="inline-form"><input value={url} placeholder="https://example.com/feed.xml" onChange={(event) => setUrl(event.target.value)} /><input value={groupName} placeholder="分组（可选）" onChange={(event) => setGroupName(event.target.value)} /><button className="primary" disabled={busy} onClick={() => void add()}>添加</button></div></section>{message && <p className={message.includes('失败') || message.includes('无法') ? 'error' : 'success'}>{message}</p>}<div className="rss-layout"><aside className="rss-feeds"><h3>订阅源</h3>{feeds.length ? feeds.map((feed) => <article key={feed.id}><div><strong>{feed.title}</strong><small>{feed.groupName || '未分组'} · {feed.lastFetchedAt ? `更新于 ${shortDate(feed.lastFetchedAt)}` : '尚未刷新'}</small>{feed.lastError && <small className="feed-error">{feed.lastError}</small>}</div><div><button className="quiet" disabled={busy} onClick={() => void window.workbench.rss.refresh(feed.id).then(refresh)}>刷新</button><button className="quiet" onClick={() => { if (window.confirm(`移除订阅“${feed.title}”？`)) void window.workbench.rss.removeFeed(feed.id).then(refresh); }}>移除</button></div></article>) : <EmptyState text="添加第一个 RSS 或 Atom 地址。" />}</aside><section className="rss-entries"><div className="page-tools"><input className="search" value={search} placeholder="搜索已缓存内容…" onChange={(event) => setSearch(event.target.value)} /><label className="rss-filter"><input type="checkbox" checked={unreadOnly} onChange={(event) => setUnreadOnly(event.target.checked)} /> 仅未读</label></div>{entries.length ? entries.map((entry) => <article className={`rss-entry ${entry.read ? 'read' : ''}`} key={entry.id}><button className="rss-entry-main" onClick={() => { void window.workbench.rss.markRead(entry.id, true).then(refresh); if (entry.link) void window.workbench.shell.openExternal(entry.link); }}><span>{entry.feedTitle}</span><strong>{entry.title}</strong><p>{entry.summary || '暂无摘要'}</p><small>{entry.publishedAt ? shortDate(entry.publishedAt) : '未知日期'}</small></button><div><button className="quiet" title="标记已读/未读" onClick={() => void window.workbench.rss.markRead(entry.id, !entry.read).then(refresh)}>{entry.read ? '未读' : '已读'}</button><button className={`quiet ${entry.starred ? 'starred' : ''}`} title="收藏" onClick={() => void window.workbench.rss.toggleStar(entry.id).then(refresh)}>★</button></div></article>) : <EmptyState text="暂无符合条件的文章。" />}</section></div></div>;
}
