import { randomUUID } from 'node:crypto';
import { mkdirSync } from 'node:fs';
import path from 'node:path';
import SqlCipher from 'better-sqlite3-multiple-ciphers';
import type { CalendarData, CreateNoteInput, CreatePromptInput, CreateTaskInput, Dashboard, FileRoot, FocusSession, GtdStage, Habit, HabitDay, HydrationDay, HydrationSettings, IndexedFile, Note, Project, PromptCategory, PromptTemplate, Tag, Task, TaskStatus, WeeklyReport } from '../shared/types';

type Db = any;
const now = () => new Date().toISOString();
const id = () => randomUUID();
const localDay = (value: Date | string = new Date()) => {
  const date = typeof value === 'string' ? new Date(value) : value;
  return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;
};

/** Encrypted SQLite gateway. Domain methods keep renderer IPC free of SQL details. */
export class WorkbenchDatabase {
  private db: Db | null = null;
  constructor(private readonly root: string) {}
  get open() { return this.db !== null; }
  private get d(): Db { if (!this.db) throw new Error('工作站已锁定，请先输入主密码。'); return this.db; }

  openWithKey(key: string) {
    mkdirSync(this.root, { recursive: true });
    const db = new SqlCipher(path.join(this.root, 'data.db'));
    db.pragma("cipher = 'sqlcipher'"); db.pragma(`key = "x'${key}'"`); db.pragma('cipher_compatibility = 4');
    db.pragma('foreign_keys = ON'); db.pragma('journal_mode = WAL');
    db.exec(`CREATE TABLE IF NOT EXISTS projects (id TEXT PRIMARY KEY, name TEXT NOT NULL UNIQUE, color TEXT NOT NULL, created_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS tags (id TEXT PRIMARY KEY, name TEXT NOT NULL UNIQUE, color TEXT NOT NULL, created_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS tasks (id TEXT PRIMARY KEY, title TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', status TEXT NOT NULL, priority TEXT NOT NULL, project_id TEXT REFERENCES projects(id) ON DELETE SET NULL, due_at TEXT, reminder_at TEXT, repeat_rule TEXT NOT NULL DEFAULT 'none', completed_at TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, gtd_stage TEXT NOT NULL DEFAULT 'inbox', important INTEGER NOT NULL DEFAULT 0, urgent INTEGER NOT NULL DEFAULT 0, reminded_at TEXT);
      CREATE TABLE IF NOT EXISTS task_tags (task_id TEXT NOT NULL REFERENCES tasks(id) ON DELETE CASCADE, tag_id TEXT NOT NULL REFERENCES tags(id) ON DELETE CASCADE, PRIMARY KEY(task_id, tag_id));
      CREATE TABLE IF NOT EXISTS notes (id TEXT PRIMARY KEY, title TEXT NOT NULL, content TEXT NOT NULL DEFAULT '', project_id TEXT REFERENCES projects(id) ON DELETE SET NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS note_tags (note_id TEXT NOT NULL REFERENCES notes(id) ON DELETE CASCADE, tag_id TEXT NOT NULL REFERENCES tags(id) ON DELETE CASCADE, PRIMARY KEY(note_id, tag_id));
      CREATE TABLE IF NOT EXISTS attachments (id TEXT PRIMARY KEY, note_id TEXT NOT NULL REFERENCES notes(id) ON DELETE CASCADE, filename TEXT NOT NULL, stored_name TEXT NOT NULL, mime_type TEXT, created_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS prompt_categories (id TEXT PRIMARY KEY, name TEXT NOT NULL UNIQUE, sort_order INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS prompts (id TEXT PRIMARY KEY, title TEXT NOT NULL, body TEXT NOT NULL, category_id TEXT REFERENCES prompt_categories(id) ON DELETE SET NULL, favorite INTEGER NOT NULL DEFAULT 0, usage_count INTEGER NOT NULL DEFAULT 0, last_used_at TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS prompt_tags (prompt_id TEXT NOT NULL REFERENCES prompts(id) ON DELETE CASCADE, tag_id TEXT NOT NULL REFERENCES tags(id) ON DELETE CASCADE, PRIMARY KEY(prompt_id, tag_id));
      CREATE TABLE IF NOT EXISTS pomodoro_sessions (id TEXT PRIMARY KEY, task_id TEXT REFERENCES tasks(id) ON DELETE SET NULL, kind TEXT NOT NULL, planned_seconds INTEGER NOT NULL, started_at TEXT NOT NULL, paused_at TEXT, paused_seconds INTEGER NOT NULL DEFAULT 0, ended_at TEXT, abandoned INTEGER NOT NULL DEFAULT 0);
      CREATE TABLE IF NOT EXISTS habits (id TEXT PRIMARY KEY, name TEXT NOT NULL, color TEXT NOT NULL, target_days INTEGER NOT NULL DEFAULT 7, archived INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS habit_days (habit_id TEXT NOT NULL REFERENCES habits(id) ON DELETE CASCADE, day TEXT NOT NULL, completed INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(habit_id, day));
      CREATE TABLE IF NOT EXISTS hydration_logs (id TEXT PRIMARY KEY, day TEXT NOT NULL, amount INTEGER NOT NULL, created_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS file_roots (id TEXT PRIMARY KEY, path TEXT NOT NULL UNIQUE, name TEXT NOT NULL, enabled INTEGER NOT NULL DEFAULT 1, last_indexed_at TEXT, created_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS indexed_files (id TEXT PRIMARY KEY, root_id TEXT NOT NULL REFERENCES file_roots(id) ON DELETE CASCADE, path TEXT NOT NULL UNIQUE, name TEXT NOT NULL, extension TEXT NOT NULL, size INTEGER NOT NULL, modified_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT NOT NULL);`);
    for (const statement of ["ALTER TABLE tasks ADD COLUMN gtd_stage TEXT NOT NULL DEFAULT 'inbox'", 'ALTER TABLE tasks ADD COLUMN important INTEGER NOT NULL DEFAULT 0', 'ALTER TABLE tasks ADD COLUMN urgent INTEGER NOT NULL DEFAULT 0', 'ALTER TABLE tasks ADD COLUMN reminded_at TEXT']) {
      try { db.exec(statement); } catch { /* existing 1.0 columns */ }
    }
    const count = (db.prepare('SELECT COUNT(*) AS count FROM prompt_categories').get() as { count: number }).count;
    if (!count) ['数据准备', '训练与微调', '量化与部署', '调试与分析'].forEach((name, sortOrder) => db.prepare('INSERT INTO prompt_categories VALUES (?, ?, ?, ?)').run(id(), name, sortOrder, now()));
    this.db = db;
  }
  close() { if (this.db) { this.db.close(); this.db = null; } }

  private tagsFor(kind: 'task' | 'note' | 'prompt', entityId: string): Tag[] {
    const table = kind === 'task' ? 'task_tags' : kind === 'note' ? 'note_tags' : 'prompt_tags'; const key = kind === 'prompt' ? 'prompt_id' : `${kind}_id`;
    return this.d.prepare(`SELECT t.* FROM tags t JOIN ${table} et ON et.tag_id=t.id WHERE et.${key}=? ORDER BY t.name`).all(entityId).map((row: any) => ({ id: row.id, name: row.name, color: row.color, createdAt: row.created_at }));
  }
  private replaceTags(kind: 'task' | 'note' | 'prompt', entityId: string, tagIds: string[] = []) {
    const table = kind === 'task' ? 'task_tags' : kind === 'note' ? 'note_tags' : 'prompt_tags'; const key = kind === 'prompt' ? 'prompt_id' : `${kind}_id`;
    const transaction = this.d.transaction(() => { this.d.prepare(`DELETE FROM ${table} WHERE ${key}=?`).run(entityId); const insert = this.d.prepare(`INSERT OR IGNORE INTO ${table} (${key}, tag_id) VALUES (?, ?)`); tagIds.forEach((tagId) => insert.run(entityId, tagId)); }); transaction();
  }
  private task(row: any): Task { return { id: row.id, title: row.title, description: row.description, status: row.status, priority: row.priority, projectId: row.project_id, projectName: row.project_name, tags: this.tagsFor('task', row.id), dueAt: row.due_at, reminderAt: row.reminder_at, repeatRule: row.repeat_rule, completedAt: row.completed_at, createdAt: row.created_at, updatedAt: row.updated_at, gtdStage: (row.gtd_stage || 'inbox') as GtdStage, important: Boolean(row.important), urgent: Boolean(row.urgent) }; }
  private note(row: any): Note { return { id: row.id, title: row.title, content: row.content, projectId: row.project_id, projectName: row.project_name, tags: this.tagsFor('note', row.id), createdAt: row.created_at, updatedAt: row.updated_at }; }
  private prompt(row: any): PromptTemplate { return { id: row.id, title: row.title, body: row.body, categoryId: row.category_id, categoryName: row.category_name, tags: this.tagsFor('prompt', row.id), favorite: Boolean(row.favorite), usageCount: row.usage_count, lastUsedAt: row.last_used_at, createdAt: row.created_at, updatedAt: row.updated_at }; }
  private taskQuery() { return 'SELECT tasks.*, projects.name AS project_name FROM tasks LEFT JOIN projects ON projects.id=tasks.project_id'; }

  listProjects(): Project[] { return this.d.prepare('SELECT * FROM projects ORDER BY name').all().map((row: any) => ({ id: row.id, name: row.name, color: row.color, createdAt: row.created_at })); }
  saveProject(input: Omit<Project, 'id' | 'createdAt'> & { id?: string }): Project { const projectId = input.id || id(); if (!input.name.trim()) throw new Error('项目名称不能为空。'); if (input.id) this.d.prepare('UPDATE projects SET name=?, color=? WHERE id=?').run(input.name.trim(), input.color || '#6d92e7', projectId); else this.d.prepare('INSERT INTO projects VALUES (?, ?, ?, ?)').run(projectId, input.name.trim(), input.color || '#6d92e7', now()); return this.listProjects().find((value) => value.id === projectId)!; }
  deleteProject(projectId: string) { this.d.prepare('DELETE FROM projects WHERE id=?').run(projectId); }
  listTags(): Tag[] { return this.d.prepare('SELECT * FROM tags ORDER BY name').all().map((row: any) => ({ id: row.id, name: row.name, color: row.color, createdAt: row.created_at })); }
  saveTag(input: Omit<Tag, 'id' | 'createdAt'> & { id?: string }): Tag { const tagId = input.id || id(); if (!input.name.trim()) throw new Error('标签名称不能为空。'); if (input.id) this.d.prepare('UPDATE tags SET name=?, color=? WHERE id=?').run(input.name.trim(), input.color || '#87a9f5', tagId); else this.d.prepare('INSERT INTO tags VALUES (?, ?, ?, ?)').run(tagId, input.name.trim(), input.color || '#87a9f5', now()); return this.listTags().find((value) => value.id === tagId)!; }
  deleteTag(tagId: string) { this.d.prepare('DELETE FROM tags WHERE id=?').run(tagId); }

  listTasks(search = ''): Task[] { const value = `%${search.trim()}%`; return this.d.prepare(`${this.taskQuery()} WHERE tasks.title LIKE ? OR tasks.description LIKE ? ORDER BY CASE tasks.status WHEN 'in_progress' THEN 0 WHEN 'todo' THEN 1 ELSE 2 END, CASE tasks.priority WHEN 'high' THEN 0 WHEN 'medium' THEN 1 ELSE 2 END, COALESCE(tasks.due_at, '9999')`).all(value, value).map((row: any) => this.task(row)); }
  getTask(taskId: string) { const row = this.d.prepare(`${this.taskQuery()} WHERE tasks.id=?`).get(taskId); return row ? this.task(row) : null; }
  saveTask(input: CreateTaskInput & { id?: string }): Task {
    const timestamp = now(); const taskId = input.id || id(); if (!input.title.trim()) throw new Error('任务标题不能为空。'); const existing = input.id ? this.getTask(input.id) : null;
    const values = { status: input.status || existing?.status || 'todo', priority: input.priority || existing?.priority || 'medium', gtdStage: input.gtdStage || existing?.gtdStage || 'inbox', important: input.important ?? existing?.important ?? false, urgent: input.urgent ?? existing?.urgent ?? false };
    if (input.id) this.d.prepare('UPDATE tasks SET title=?, description=?, status=?, priority=?, project_id=?, due_at=?, reminder_at=?, repeat_rule=?, gtd_stage=?, important=?, urgent=?, reminded_at=NULL, updated_at=? WHERE id=?').run(input.title.trim(), input.description || '', values.status, values.priority, input.projectId || null, input.dueAt || null, input.reminderAt || null, input.repeatRule || 'none', values.gtdStage, values.important ? 1 : 0, values.urgent ? 1 : 0, timestamp, taskId);
    else this.d.prepare('INSERT INTO tasks (id,title,description,status,priority,project_id,due_at,reminder_at,repeat_rule,completed_at,created_at,updated_at,gtd_stage,important,urgent,reminded_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, NULL, ?, ?, ?, ?, ?, NULL)').run(taskId, input.title.trim(), input.description || '', values.status, values.priority, input.projectId || null, input.dueAt || null, input.reminderAt || null, input.repeatRule || 'none', timestamp, timestamp, values.gtdStage, values.important ? 1 : 0, values.urgent ? 1 : 0);
    this.replaceTags('task', taskId, input.tagIds ?? existing?.tags.map((tag) => tag.id) ?? []); return this.getTask(taskId)!;
  }
  deleteTask(taskId: string) { this.d.prepare('DELETE FROM tasks WHERE id=?').run(taskId); }
  moveTask(taskId: string, status: TaskStatus) { this.d.prepare('UPDATE tasks SET status=?, completed_at=?, updated_at=? WHERE id=?').run(status, status === 'done' ? now() : null, now(), taskId); return this.getTask(taskId)!; }
  completeTask(taskId: string) { const task = this.getTask(taskId); if (!task) throw new Error('任务不存在。'); this.moveTask(taskId, 'done'); if (task.repeatRule !== 'none') { const base = task.dueAt ? new Date(task.dueAt) : new Date(); if (task.repeatRule === 'daily') base.setDate(base.getDate() + 1); if (task.repeatRule === 'weekly') base.setDate(base.getDate() + 7); if (task.repeatRule === 'monthly') base.setMonth(base.getMonth() + 1); this.saveTask({ title: task.title, description: task.description, priority: task.priority, projectId: task.projectId, tagIds: task.tags.map((tag) => tag.id), dueAt: base.toISOString(), repeatRule: task.repeatRule, gtdStage: task.gtdStage, important: task.important, urgent: task.urgent }); } return this.getTask(taskId)!; }
  dueReminders() { return this.d.prepare(`${this.taskQuery()} WHERE tasks.status != 'done' AND tasks.reminder_at IS NOT NULL AND tasks.reminder_at <= ? AND tasks.reminded_at IS NULL`).all(now()).map((row: any) => this.task(row)); }
  markReminded(taskId: string) { this.d.prepare('UPDATE tasks SET reminded_at=? WHERE id=?').run(now(), taskId); }

  listNotes(search = ''): Note[] { const value = `%${search.trim()}%`; return this.d.prepare('SELECT notes.*, projects.name AS project_name FROM notes LEFT JOIN projects ON projects.id=notes.project_id WHERE notes.title LIKE ? OR notes.content LIKE ? ORDER BY notes.updated_at DESC').all(value, value).map((row: any) => this.note(row)); }
  getNote(noteId: string) { const row = this.d.prepare('SELECT notes.*, projects.name AS project_name FROM notes LEFT JOIN projects ON projects.id=notes.project_id WHERE notes.id=?').get(noteId); return row ? this.note(row) : null; }
  saveNote(input: CreateNoteInput & { id?: string }): Note { const timestamp = now(); const noteId = input.id || id(); if (!input.title.trim()) throw new Error('笔记标题不能为空。'); if (input.id) this.d.prepare('UPDATE notes SET title=?, content=?, project_id=?, updated_at=? WHERE id=?').run(input.title.trim(), input.content || '', input.projectId || null, timestamp, noteId); else this.d.prepare('INSERT INTO notes VALUES (?, ?, ?, ?, ?, ?)').run(noteId, input.title.trim(), input.content || '', input.projectId || null, timestamp, timestamp); this.replaceTags('note', noteId, input.tagIds); return this.getNote(noteId)!; }
  attachmentsFor(noteId: string) { return this.d.prepare('SELECT * FROM attachments WHERE note_id=?').all(noteId); }
  deleteNote(noteId: string) { const files = this.attachmentsFor(noteId); this.d.prepare('DELETE FROM notes WHERE id=?').run(noteId); return files; }
  attachment(value: string) { return this.d.prepare('SELECT * FROM attachments WHERE id=?').get(value); }
  addAttachment(noteId: string, filename: string, storedName: string, mimeType: string | null) { const attachmentId = id(); this.d.prepare('INSERT INTO attachments VALUES (?, ?, ?, ?, ?, ?)').run(attachmentId, noteId, filename, storedName, mimeType, now()); return attachmentId; }

  categories(): PromptCategory[] { return this.d.prepare('SELECT * FROM prompt_categories ORDER BY sort_order, name').all().map((row: any) => ({ id: row.id, name: row.name, sortOrder: row.sort_order, createdAt: row.created_at })); }
  listPrompts(search = ''): PromptTemplate[] { const value = `%${search.trim()}%`; return this.d.prepare('SELECT prompts.*, prompt_categories.name AS category_name FROM prompts LEFT JOIN prompt_categories ON prompt_categories.id=prompts.category_id WHERE prompts.title LIKE ? OR prompts.body LIKE ? ORDER BY prompts.favorite DESC, prompts.updated_at DESC').all(value, value).map((row: any) => this.prompt(row)); }
  savePrompt(input: CreatePromptInput & { id?: string }): PromptTemplate { const timestamp = now(); const promptId = input.id || id(); if (!input.title.trim() || !input.body.trim()) throw new Error('模板标题和内容不能为空。'); if (input.id) this.d.prepare('UPDATE prompts SET title=?, body=?, category_id=?, favorite=?, updated_at=? WHERE id=?').run(input.title.trim(), input.body, input.categoryId || null, input.favorite ? 1 : 0, timestamp, promptId); else this.d.prepare('INSERT INTO prompts VALUES (?, ?, ?, ?, ?, 0, NULL, ?, ?)').run(promptId, input.title.trim(), input.body, input.categoryId || null, input.favorite ? 1 : 0, timestamp, timestamp); this.replaceTags('prompt', promptId, input.tagIds); return this.getPrompt(promptId)!; }
  getPrompt(promptId: string) { const row = this.d.prepare('SELECT prompts.*, prompt_categories.name AS category_name FROM prompts LEFT JOIN prompt_categories ON prompt_categories.id=prompts.category_id WHERE prompts.id=?').get(promptId); return row ? this.prompt(row) : null; }
  deletePrompt(promptId: string) { this.d.prepare('DELETE FROM prompts WHERE id=?').run(promptId); }
  usePrompt(promptId: string, values: Record<string, string>) { const prompt = this.getPrompt(promptId); if (!prompt) throw new Error('模板不存在。'); const text = prompt.body.replace(/{{\s*([\w.-]+)\s*}}/g, (_, name) => values[name] ?? `{{${name}}}`); this.d.prepare('UPDATE prompts SET usage_count=usage_count+1, last_used_at=? WHERE id=?').run(now(), promptId); return text; }

  listHabits(): Habit[] { return this.d.prepare('SELECT * FROM habits WHERE archived=0 ORDER BY created_at').all().map((row: any) => ({ id: row.id, name: row.name, color: row.color, targetDays: row.target_days, archived: Boolean(row.archived), createdAt: row.created_at })); }
  saveHabit(input: Omit<Habit, 'id' | 'createdAt' | 'archived'> & { id?: string }): Habit { const habitId = input.id || id(); if (!input.name.trim()) throw new Error('习惯名称不能为空。'); if (input.id) this.d.prepare('UPDATE habits SET name=?, color=?, target_days=? WHERE id=?').run(input.name.trim(), input.color || '#74d4a5', input.targetDays || 7, habitId); else this.d.prepare('INSERT INTO habits VALUES (?, ?, ?, ?, 0, ?)').run(habitId, input.name.trim(), input.color || '#74d4a5', input.targetDays || 7, now()); return this.listHabits().find((habit) => habit.id === habitId)!; }
  deleteHabit(habitId: string) { this.d.prepare('DELETE FROM habits WHERE id=?').run(habitId); }
  habitDays(month: string): HabitDay[] { return this.d.prepare('SELECT * FROM habit_days WHERE day LIKE ? AND completed=1').all(`${month}%`).map((row: any) => ({ habitId: row.habit_id, day: row.day, completed: Boolean(row.completed) })); }
  toggleHabit(habitId: string, day: string): HabitDay { const current = this.d.prepare('SELECT completed FROM habit_days WHERE habit_id=? AND day=?').get(habitId, day); const completed = !current?.completed; this.d.prepare('INSERT INTO habit_days (habit_id, day, completed) VALUES (?, ?, ?) ON CONFLICT(habit_id, day) DO UPDATE SET completed=excluded.completed').run(habitId, day, completed ? 1 : 0); return { habitId, day, completed }; }

  hydrationSettings(): HydrationSettings { try { return { dailyGoal: 8, reminderMinutes: 60, ...JSON.parse(this.d.prepare("SELECT value FROM settings WHERE key='hydration'").get()?.value || '{}') }; } catch { return { dailyGoal: 8, reminderMinutes: 60 }; } }
  saveHydrationSettings(value: HydrationSettings) { const clean = { dailyGoal: Math.max(1, Math.min(30, Math.round(value.dailyGoal || 8))), reminderMinutes: Math.max(15, Math.min(480, Math.round(value.reminderMinutes || 60))) }; this.d.prepare("INSERT INTO settings (key,value) VALUES ('hydration',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").run(JSON.stringify(clean)); return clean; }
  hydrationDay(day = localDay()): HydrationDay { const amount = this.d.prepare('SELECT COALESCE(SUM(amount),0) AS amount FROM hydration_logs WHERE day=?').get(day).amount as number; return { day, amount, goal: this.hydrationSettings().dailyGoal }; }
  addHydration(amount = 1) { const day = localDay(); this.d.prepare('INSERT INTO hydration_logs VALUES (?, ?, ?, ?)').run(id(), day, Math.max(1, Math.min(10, Math.round(amount))), now()); return this.hydrationDay(day); }

  listFileRoots(): FileRoot[] { return this.d.prepare('SELECT * FROM file_roots ORDER BY created_at').all().map((row: any) => ({ id: row.id, path: row.path, name: row.name, enabled: Boolean(row.enabled), lastIndexedAt: row.last_indexed_at, createdAt: row.created_at })); }
  addFileRoot(rootPath: string, name: string) { const rootId = id(); this.d.prepare('INSERT OR IGNORE INTO file_roots VALUES (?, ?, ?, 1, NULL, ?)').run(rootId, rootPath, name, now()); return this.listFileRoots().find((root) => root.path === rootPath) || null; }
  removeFileRoot(rootId: string) { this.d.prepare('DELETE FROM file_roots WHERE id=?').run(rootId); }
  replaceIndexedFiles(rootId: string, files: Array<Omit<IndexedFile, 'id' | 'rootId'>>) { const transaction = this.d.transaction(() => { this.d.prepare('DELETE FROM indexed_files WHERE root_id=?').run(rootId); const insert = this.d.prepare('INSERT INTO indexed_files VALUES (?, ?, ?, ?, ?, ?, ?)'); files.forEach((file) => insert.run(id(), rootId, file.path, file.name, file.extension, file.size, file.modifiedAt)); this.d.prepare('UPDATE file_roots SET last_indexed_at=? WHERE id=?').run(now(), rootId); }); transaction(); }
  searchFiles(query: string): IndexedFile[] { const value = `%${query.trim()}%`; if (!query.trim()) return []; return this.d.prepare('SELECT indexed_files.* FROM indexed_files JOIN file_roots ON file_roots.id=indexed_files.root_id WHERE file_roots.enabled=1 AND (indexed_files.name LIKE ? OR indexed_files.path LIKE ?) ORDER BY indexed_files.modified_at DESC LIMIT 200').all(value, value).map((row: any) => ({ id: row.id, rootId: row.root_id, path: row.path, name: row.name, extension: row.extension, size: row.size, modifiedAt: row.modified_at })); }
  indexedFile(fileId: string) { return this.d.prepare('SELECT indexed_files.*, file_roots.path AS root_path FROM indexed_files JOIN file_roots ON file_roots.id=indexed_files.root_id WHERE indexed_files.id=?').get(fileId); }

  activeFocus(): FocusSession | null { const row = this.d.prepare('SELECT pomodoro_sessions.*, tasks.title AS task_title FROM pomodoro_sessions LEFT JOIN tasks ON tasks.id=pomodoro_sessions.task_id WHERE ended_at IS NULL ORDER BY started_at DESC LIMIT 1').get(); return row ? this.focus(row) : null; }
  private focus(row: any): FocusSession { return { id: row.id, taskId: row.task_id, taskTitle: row.task_title, kind: row.kind, plannedSeconds: row.planned_seconds, startedAt: row.started_at, pausedAt: row.paused_at, pausedSeconds: row.paused_seconds, endedAt: row.ended_at, abandoned: Boolean(row.abandoned) }; }
  startFocus(taskId: string | null, kind: 'focus' | 'break' = 'focus') { const existing = this.activeFocus(); if (existing) return existing; const sessionId = id(); this.d.prepare('INSERT INTO pomodoro_sessions VALUES (?, ?, ?, ?, ?, NULL, 0, NULL, 0)').run(sessionId, taskId || null, kind, kind === 'focus' ? 1500 : 300, now()); return this.activeFocus()!; }
  pauseFocus() { const focus = this.activeFocus(); if (!focus) return null; if (!focus.pausedAt) this.d.prepare('UPDATE pomodoro_sessions SET paused_at=? WHERE id=?').run(now(), focus.id); else { const paused = Math.round((Date.now() - new Date(focus.pausedAt).getTime()) / 1000); this.d.prepare('UPDATE pomodoro_sessions SET paused_at=NULL, paused_seconds=paused_seconds+? WHERE id=?').run(paused, focus.id); } return this.activeFocus(); }
  finishFocus(abandoned = false) { const focus = this.activeFocus(); if (!focus) return null; let pausedSeconds = focus.pausedSeconds; if (focus.pausedAt) pausedSeconds += Math.round((Date.now() - new Date(focus.pausedAt).getTime()) / 1000); this.d.prepare('UPDATE pomodoro_sessions SET paused_at=NULL, paused_seconds=?, ended_at=?, abandoned=? WHERE id=?').run(pausedSeconds, now(), abandoned ? 1 : 0, focus.id); const row = this.d.prepare('SELECT pomodoro_sessions.*, tasks.title AS task_title FROM pomodoro_sessions LEFT JOIN tasks ON tasks.id=pomodoro_sessions.task_id WHERE pomodoro_sessions.id=?').get(focus.id); return row ? this.focus(row) : null; }

  calendar(month: string): CalendarData { return { tasks: this.listTasks().filter((task) => task.dueAt && localDay(task.dueAt).startsWith(month)), habits: this.listHabits(), habitDays: this.habitDays(month) }; }
  dashboard(): Dashboard { const day = localDay(); const tasks = this.listTasks(); return { todayTasks: tasks.filter((task) => task.status !== 'done' && task.dueAt && localDay(task.dueAt) === day), overdueTasks: tasks.filter((task) => task.status !== 'done' && task.dueAt && localDay(task.dueAt) < day), recentNotes: this.listNotes().slice(0, 5), favoritePrompts: this.listPrompts().filter((prompt) => prompt.favorite).slice(0, 5), weekFocusSeconds: this.weekFocusSeconds(), activeFocus: this.activeFocus() }; }
  private weekStart() { const date = new Date(); const weekday = date.getDay() || 7; date.setHours(0, 0, 0, 0); date.setDate(date.getDate() - weekday + 1); return date; }
  private weekFocusSeconds() { const rows = this.d.prepare('SELECT * FROM pomodoro_sessions WHERE ended_at IS NOT NULL AND started_at >= ? AND abandoned=0').all(this.weekStart().toISOString()); return rows.reduce((total: number, row: any) => total + Math.max(0, Math.round((new Date(row.ended_at).getTime() - new Date(row.started_at).getTime()) / 1000) - row.paused_seconds), 0); }
  weeklyReport(): WeeklyReport { const start = this.weekStart().toISOString(); const completed: Task[] = this.d.prepare(`${this.taskQuery()} WHERE tasks.completed_at >= ? ORDER BY tasks.completed_at DESC`).all(start).map((row: any) => this.task(row)); const pending: Task[] = this.listTasks().filter((task) => task.status !== 'done'); const stats = this.d.prepare("SELECT COALESCE(projects.name, '未分类') AS name, COUNT(*) AS count FROM tasks LEFT JOIN projects ON projects.id=tasks.project_id WHERE tasks.completed_at >= ? GROUP BY projects.name ORDER BY count DESC").all(start) as Array<{ name: string; count: number }>; const tagStats = this.d.prepare('SELECT tags.name AS name, COUNT(*) AS count FROM task_tags JOIN tags ON tags.id=task_tags.tag_id JOIN tasks ON tasks.id=task_tags.task_id WHERE tasks.completed_at >= ? GROUP BY tags.id ORDER BY count DESC').all(start) as Array<{ name: string; count: number }>; const focusSeconds = this.weekFocusSeconds(); const markdown = `# 本周工作周报\n\n> ${this.weekStart().toLocaleDateString()} — ${new Date().toLocaleDateString()}\n\n## 完成任务（${completed.length}）\n${completed.length ? completed.map((task: Task) => `- [x] ${task.title}`).join('\n') : '- 本周暂无已完成任务'}\n\n## 项目统计\n${stats.length ? stats.map((stat) => `- ${stat.name}：${stat.count} 项任务`).join('\n') : '- 暂无数据'}\n\n## 标签统计\n${tagStats.length ? tagStats.map((stat) => `- ${stat.name}：${stat.count} 项任务`).join('\n') : '- 暂无数据'}\n\n## 专注时间\n- 番茄专注总时长：${(focusSeconds / 3600).toFixed(1)} 小时\n\n## 下周待办\n${pending.length ? pending.map((task: Task) => `- [ ] ${task.title}`).join('\n') : '- 暂无待办'}`; return { markdown, completed, pending, focusSeconds, projectStats: stats, tagStats }; }
  checkpoint() { this.d.pragma('wal_checkpoint(TRUNCATE)'); }
}
