import { app, BrowserWindow, Notification, clipboard, dialog, ipcMain, shell } from 'electron';
import type { CreateNoteInput, CreatePromptInput, CreateTaskInput, TaskStatus } from '../shared/types';
import { WorkbenchServices } from './services';
import { createDatabaseKey, hasEnvelope, unwrapDatabaseKey } from './security';

export function registerIpc(services: WorkbenchServices, emit: (channel: 'locked' | 'focus-changed' | 'navigate', value?: string) => void) {
  const requireOpen = () => { if (!services.database.open) throw new Error('工作站已锁定。'); };
  ipcMain.handle('app:info', () => ({ name: app.getName(), version: app.getVersion(), dataDirectory: services.root }));
  ipcMain.handle('auth:state', () => ({ configured: hasEnvelope(services.root), unlocked: services.database.open }));
  ipcMain.handle('auth:setup', (_, password: string) => { if (hasEnvelope(services.root)) throw new Error('工作站已经初始化。'); const key = createDatabaseKey(services.root, password); services.database.openWithKey(key); void services.rescanFiles().catch((): void => { void 0; }); void services.maybeSendWeeklyMail().catch((): void => { void 0; }); void services.maybeAutoRemoteBackup().catch((): void => { void 0; }); });
  ipcMain.handle('auth:unlock', (_, password: string) => { const key = unwrapDatabaseKey(services.root, password); services.database.openWithKey(key); void services.rescanFiles().catch((): void => { void 0; }); void services.maybeSendWeeklyMail().catch((): void => { void 0; }); void services.maybeAutoRemoteBackup().catch((): void => { void 0; }); });
  ipcMain.handle('auth:lock', () => { services.database.close(); emit('locked'); });
  ipcMain.handle('tasks:list', (_, search?: string) => { requireOpen(); return services.database.listTasks(search); });
  ipcMain.handle('tasks:save', (_, input: CreateTaskInput & { id?: string }) => { requireOpen(); return services.database.saveTask(input); });
  ipcMain.handle('tasks:remove', (_, taskId: string) => { requireOpen(); services.database.deleteTask(taskId); });
  ipcMain.handle('tasks:complete', (_, taskId: string) => { requireOpen(); return services.database.completeTask(taskId); });
  ipcMain.handle('tasks:move', (_, taskId: string, status: TaskStatus) => { requireOpen(); return services.database.moveTask(taskId, status); });
  ipcMain.handle('projects:list', () => { requireOpen(); return services.database.listProjects(); });
  ipcMain.handle('projects:save', (_, input) => { requireOpen(); return services.database.saveProject(input); });
  ipcMain.handle('projects:remove', (_, projectId: string) => { requireOpen(); services.database.deleteProject(projectId); });
  ipcMain.handle('tags:list', () => { requireOpen(); return services.database.listTags(); });
  ipcMain.handle('tags:save', (_, input) => { requireOpen(); return services.database.saveTag(input); });
  ipcMain.handle('tags:remove', (_, tagId: string) => { requireOpen(); services.database.deleteTag(tagId); });
  ipcMain.handle('notes:list', (_, search?: string) => { requireOpen(); return services.database.listNotes(search); });
  ipcMain.handle('notes:get', (_, noteId: string) => { requireOpen(); return services.database.getNote(noteId); });
  ipcMain.handle('notes:save', (_, input: CreateNoteInput & { id?: string }) => { requireOpen(); return services.database.saveNote(input); });
  ipcMain.handle('notes:remove', async (_, noteId: string) => { requireOpen(); await services.removeNote(noteId); });
  ipcMain.handle('notes:attach', async (_, noteId: string) => { requireOpen(); return services.addAttachment(noteId); });
  ipcMain.handle('prompts:list', (_, search?: string) => { requireOpen(); return services.database.listPrompts(search); });
  ipcMain.handle('prompts:categories', () => { requireOpen(); return services.database.categories(); });
  ipcMain.handle('prompts:save', (_, input: CreatePromptInput & { id?: string }) => { requireOpen(); return services.database.savePrompt(input); });
  ipcMain.handle('prompts:remove', (_, promptId: string) => { requireOpen(); services.database.deletePrompt(promptId); });
  ipcMain.handle('prompts:use', (_, promptId: string, values: Record<string, string>) => { requireOpen(); const text = services.database.usePrompt(promptId, values); clipboard.writeText(text); return text; });
  ipcMain.handle('focus:active', () => { requireOpen(); return services.database.activeFocus(); });
  ipcMain.handle('focus:start', (_, taskId?: string | null, kind?: 'focus' | 'break') => { requireOpen(); const value = services.database.startFocus(taskId || null, kind); emit('focus-changed'); return value; });
  ipcMain.handle('focus:pause', () => { requireOpen(); const value = services.database.pauseFocus(); emit('focus-changed'); return value; });
  ipcMain.handle('focus:finish', (_, abandoned?: boolean) => { requireOpen(); const value = services.database.finishFocus(abandoned); if (value && !abandoned) new Notification({ title: value.kind === 'focus' ? '专注完成' : '休息结束', body: value.kind === 'focus' ? '做得好，休息一下吧。' : '准备开始下一轮专注。' }).show(); emit('focus-changed'); return value; });
  ipcMain.handle('dashboard:get', () => { requireOpen(); return services.database.dashboard(); });
  ipcMain.handle('reports:weekly', () => { requireOpen(); return services.database.weeklyReport(); });
  ipcMain.handle('reports:save-weekly', () => { requireOpen(); return services.saveReport(services.database.weeklyReport().markdown); });
  ipcMain.handle('reports:copy', (_, text: string) => services.copy(text));
  ipcMain.handle('backup:export', () => { requireOpen(); return services.exportBackup(); });
  ipcMain.handle('backup:restore', async () => { requireOpen(); const owner = BrowserWindow.getFocusedWindow(); const choice = await dialog.showMessageBox(owner || undefined, { type: 'warning', buttons: ['取消', '继续恢复'], defaultId: 0, cancelId: 0, message: '恢复备份会替换当前所有工作站数据。', detail: '恢复后应用将重启，并要求输入该备份原有的主密码。' }); if (choice.response === 1) await services.restoreBackup(); });
  ipcMain.handle('calendar:get', (_, month: string) => { requireOpen(); return services.database.calendar(month); });
  ipcMain.handle('habits:list', () => { requireOpen(); return services.database.listHabits(); });
  ipcMain.handle('habits:save', (_, input) => { requireOpen(); return services.database.saveHabit(input); });
  ipcMain.handle('habits:remove', (_, habitId: string) => { requireOpen(); services.database.deleteHabit(habitId); });
  ipcMain.handle('habits:toggle', (_, habitId: string, day: string) => { requireOpen(); return services.database.toggleHabit(habitId, day); });
  ipcMain.handle('habits:days', (_, month: string) => { requireOpen(); return services.database.habitDays(month); });
  ipcMain.handle('hydration:get', (_, day: string) => { requireOpen(); return services.database.hydrationDay(day); });
  ipcMain.handle('hydration:add', (_, amount?: number) => { requireOpen(); return services.database.addHydration(amount); });
  ipcMain.handle('hydration:settings', () => { requireOpen(); return services.database.hydrationSettings(); });
  ipcMain.handle('hydration:save-settings', (_, input) => { requireOpen(); return services.database.saveHydrationSettings(input); });
  ipcMain.handle('files:roots', () => { requireOpen(); return services.database.listFileRoots(); });
  ipcMain.handle('files:add-root', () => { requireOpen(); return services.addFileRoot(); });
  ipcMain.handle('files:remove-root', (_, rootId: string) => { requireOpen(); services.database.removeFileRoot(rootId); });
  ipcMain.handle('files:rescan', async () => { requireOpen(); await services.rescanFiles(); });
  ipcMain.handle('files:search', (_, query: string) => { requireOpen(); return services.database.searchFiles(query); });
  ipcMain.handle('files:open', (_, fileId: string) => { requireOpen(); return services.openIndexedFile(fileId); });
  ipcMain.handle('notes:open-attachment', (_, attachmentId: string) => { requireOpen(); return services.openAttachment(attachmentId); });
  ipcMain.handle('rss:feeds', () => { requireOpen(); return services.database.listRssFeeds(); });
  ipcMain.handle('rss:save', (_, input) => { requireOpen(); return services.database.saveRssFeed(input); });
  ipcMain.handle('rss:remove', (_, feedId: string) => { requireOpen(); services.database.deleteRssFeed(feedId); });
  ipcMain.handle('rss:refresh', async (_, feedId?: string) => { requireOpen(); await services.refreshRss(feedId); });
  ipcMain.handle('rss:entries', (_, input) => { requireOpen(); return services.database.listRssEntries(input); });
  ipcMain.handle('rss:mark-read', (_, entryId: string, read: boolean) => { requireOpen(); services.database.markRssEntryRead(entryId, read); });
  ipcMain.handle('rss:toggle-star', (_, entryId: string) => { requireOpen(); services.database.toggleRssEntryStar(entryId); });
  ipcMain.handle('mail:settings', () => { requireOpen(); return services.mailSettings(); });
  ipcMain.handle('mail:save-settings', (_, input) => { requireOpen(); return services.saveMailSettings(input); });
  ipcMain.handle('mail:test', async () => { requireOpen(); await services.sendWeeklyMail(false); });
  ipcMain.handle('mail:send-weekly', async () => { requireOpen(); await services.sendWeeklyMail(false); });
  ipcMain.handle('mail:clear', async () => { requireOpen(); await services.clearMailSettings(); });
  ipcMain.handle('remote-backup:config', () => { requireOpen(); return services.remoteBackupConfig(); });
  ipcMain.handle('remote-backup:save-config', (_, input) => { requireOpen(); return services.saveRemoteBackupConfig(input); });
  ipcMain.handle('remote-backup:test', async () => { requireOpen(); await services.testRemoteBackup(); });
  ipcMain.handle('remote-backup:backup', (_, automatic?: boolean) => { requireOpen(); return services.backupRemote(Boolean(automatic)); });
  ipcMain.handle('remote-backup:list', (_, search?: string) => { requireOpen(); return services.listRemoteBackups(search); });
  ipcMain.handle('remote-backup:restore', async (_, key: string) => { requireOpen(); const choice = await dialog.showMessageBox(BrowserWindow.getFocusedWindow() || undefined, { type: 'warning', buttons: ['取消', '下载并恢复'], defaultId: 0, cancelId: 0, message: '远程恢复会替换当前所有工作站数据。', detail: '恢复后应用将重启，并要求输入备份原有的主密码。' }); if (choice.response === 1) await services.restoreRemoteBackup(key); });
  ipcMain.handle('remote-backup:clear', async () => { requireOpen(); await services.clearRemoteBackupConfig(); });
  ipcMain.handle('updates:check', () => services.updates.check(app.getVersion()));
  ipcMain.handle('updates:download', () => services.downloadUpdate());
  ipcMain.handle('shell:open-external', (_, raw: string) => { try { const url = new URL(raw); if (url.protocol === 'https:') return shell.openExternal(url.toString()); } catch { /* invalid addresses are ignored */ } });
  ipcMain.handle('shell:quick-create', (_, type: 'task' | 'note') => emit('navigate', `/${type}s?new=1`));
}
