import { useEffect, useState } from 'react';
import { HashRouter, Navigate, NavLink, Route, Routes, useLocation, useNavigate } from 'react-router-dom';
import CodeMirror from '@uiw/react-codemirror';
import { markdown } from '@codemirror/lang-markdown';
import { oneDark } from '@codemirror/theme-one-dark';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import rehypeSanitize from 'rehype-sanitize';
import type { Dashboard, FocusSession, Note, PromptTemplate, Task, TaskPriority, TaskStatus, WeeklyReport } from './shared/types';
import { FocusPill } from './renderer/components/FocusPill';
import { Dialog } from './renderer/components/Dialog';
import { EmptyState as Empty } from './renderer/components/EmptyState';

const labels: Record<string, string> = { '/': '今日总览', '/tasks': '任务', '/notes': '笔记', '/prompts': '提示词模板', '/reports': '统计周报', '/settings': '设置' };
const icons: Record<string, string> = { '/': '◈', '/tasks': '✓', '/notes': '▤', '/prompts': '⌘', '/reports': '◫', '/settings': '⚙' };
const shortDate = (value?: string | null) => value ? new Intl.DateTimeFormat('zh-CN', { month: 'short', day: 'numeric' }).format(new Date(value)) : '未设置';
const taskStatus: Record<TaskStatus, string> = { todo: '待处理', in_progress: '进行中', done: '已完成' };
const priorityText: Record<TaskPriority, string> = { high: '高', medium: '中', low: '低' };

function AuthGate() {
  const [state, setState] = useState<'loading' | 'setup' | 'unlock' | 'ready'>('loading');
  const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [error, setError] = useState('');
  useEffect(() => { void window.workbench.auth.state().then((x) => setState(x.unlocked ? 'ready' : x.configured ? 'unlock' : 'setup')); const unsubscribe = window.workbench.events.onLocked(() => { setPassword(''); setState('unlock'); }); return unsubscribe; }, []);
  if (state === 'ready') return <Workbench />;
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setError(''); try { if (state === 'setup') { if (password !== confirm) throw new Error('两次输入的主密码不一致。'); await window.workbench.auth.setup(password); } else await window.workbench.auth.unlock(password); setPassword(''); setConfirm(''); setState('ready'); } catch (e: any) { setError(e.message || '无法解锁工作站。'); } };
  return <main className="auth-shell"><section className="auth-card"><span className="brand-mark">Z</span><p className="eyebrow">ZZZ WORKSTATION</p><h1>{state === 'setup' ? '创建你的私密工作站' : '欢迎回来'}</h1><p className="muted">{state === 'setup' ? '主密码用于加密所有本地数据，忘记后无法恢复。' : '请输入主密码以解锁本地加密数据。'}</p><form onSubmit={submit}><label>主密码<input type="password" value={password} minLength={10} onChange={(e) => setPassword(e.target.value)} autoFocus required /></label>{state === 'setup' && <label>确认主密码<input type="password" value={confirm} minLength={10} onChange={(e) => setConfirm(e.target.value)} required /></label>}{error && <p className="error">{error}</p>}<button className="primary full" type="submit">{state === 'setup' ? '创建并进入工作站' : '解锁工作站'}</button></form></section></main>;
}

function Workbench() {
  const navigate = useNavigate(); const location = useLocation(); const [focus, setFocus] = useState<FocusSession | null>(null);
  const refreshFocus = () => window.workbench.focus.active().then(setFocus).catch(() => setFocus(null));
  useEffect(() => { void refreshFocus(); const unsubscribe = window.workbench.events.onFocusChanged(refreshFocus); const route = window.workbench.events.onNavigate((target) => navigate(target)); return () => { unsubscribe(); route(); }; }, [navigate]);
  const lock = async () => { await window.workbench.auth.lock(); };
  return <div className="app-shell"><aside className="sidebar"><div className="logo"><span className="brand-mark small">Z</span><span>Zzz 的工作站</span></div><nav>{Object.keys(labels).map((path) => <NavLink key={path} to={path} end={path === '/'} className={({ isActive }) => `nav-item ${isActive ? 'active' : ''}`}><span>{icons[path]}</span>{labels[path]}</NavLink>)}</nav><div className="sidebar-bottom"><button className="quiet" onClick={() => navigate('/tasks?new=1')}>＋ 新建任务</button><button className="quiet" onClick={() => navigate('/notes?new=1')}>＋ 新建笔记</button></div></aside><main className="content"><header className="topbar"><div><p className="eyebrow">本地加密 · 离线优先</p><h2>{labels[location.pathname] || 'Zzz 的工作站'}</h2></div><div className="top-actions"><FocusPill focus={focus} refreshed={refreshFocus} /><button className="quiet" onClick={lock}>锁定</button></div></header><Routes><Route path="/" element={<DashboardPage navigate={navigate} />} /><Route path="/tasks" element={<TasksPage />} /><Route path="/notes" element={<NotesPage />} /><Route path="/prompts" element={<PromptsPage />} /><Route path="/reports" element={<ReportsPage />} /><Route path="/settings" element={<SettingsPage />} /><Route path="*" element={<Navigate to="/" replace />} /></Routes></main></div>;
}

function DashboardPage({ navigate }: { navigate: (path: string) => void }) {
  const [data, setData] = useState<Dashboard | null>(null); useEffect(() => { void window.workbench.dashboard.get().then(setData); }, []);
  if (!data) return <Loading />;
  return <div className="page dashboard"><section className="welcome"><div><p className="eyebrow">{new Intl.DateTimeFormat('zh-CN', { weekday: 'long', month: 'long', day: 'numeric' }).format(new Date())}</p><h1>把今天过得清晰一点。</h1></div><div className="week-focus"><span>本周专注</span><strong>{(data.weekFocusSeconds / 3600).toFixed(1)} h</strong></div></section><div className="metric-grid"><Metric label="今日待办" value={data.todayTasks.length} tone="blue" /><Metric label="逾期任务" value={data.overdueTasks.length} tone="red" /><Metric label="最近笔记" value={data.recentNotes.length} tone="purple" /><Metric label="常用模板" value={data.favoritePrompts.length} tone="green" /></div><section className="two-columns"><Panel title="今日待办" action="查看全部" onAction={() => navigate('/tasks')}><TaskRows tasks={data.todayTasks} empty="今天没有截止任务，给自己留一点空间。" /></Panel><Panel title="逾期任务" action="处理任务" onAction={() => navigate('/tasks')}><TaskRows tasks={data.overdueTasks} empty="很好，没有逾期任务。" /></Panel></section><section className="two-columns"><Panel title="最近笔记" action="新建笔记" onAction={() => navigate('/notes?new=1')}><div className="compact-list">{data.recentNotes.length ? data.recentNotes.map((n) => <div className="compact-row" key={n.id}><span>▤</span><div><strong>{n.title}</strong><small>{shortDate(n.updatedAt)}</small></div></div>) : <Empty text="从一条速记开始。" />}</div></Panel><Panel title="常用模板" action="管理模板" onAction={() => navigate('/prompts')}><div className="compact-list">{data.favoritePrompts.length ? data.favoritePrompts.map((p) => <div className="compact-row" key={p.id}><span>⌘</span><div><strong>{p.title}</strong><small>{p.categoryName || '未分类'} · 已使用 {p.usageCount} 次</small></div></div>) : <Empty text="收藏常用提示词会显示在这里。" />}</div></Panel></section></div>;
}

function TasksPage() {
  const [tasks, setTasks] = useState<Task[]>([]); const [search, setSearch] = useState(''); const [view, setView] = useState<'list' | 'board'>('list'); const [editing, setEditing] = useState<Task | null>(null); const refresh = () => window.workbench.tasks.list(search).then(setTasks);
  useEffect(() => { void refresh(); }, [search]);
  const complete = async (id: string) => { await window.workbench.tasks.complete(id); refresh(); };
  return <div className="page"><div className="page-tools"><input className="search" placeholder="搜索任务…" value={search} onChange={(e) => setSearch(e.target.value)} /><div className="segmented"><button className={view === 'list' ? 'selected' : ''} onClick={() => setView('list')}>列表</button><button className={view === 'board' ? 'selected' : ''} onClick={() => setView('board')}>看板</button></div><button className="primary" onClick={() => setEditing({} as Task)}>＋ 新建任务</button></div>{view === 'list' ? <div className="task-list">{tasks.length ? tasks.map((task) => <TaskRow key={task.id} task={task} onComplete={complete} onEdit={setEditing} />) : <Empty text="还没有任务。把最重要的一件事写下来。" />}</div> : <Kanban tasks={tasks} refresh={refresh} edit={setEditing} />}{editing && <TaskDialog task={editing.id ? editing : null} onClose={() => setEditing(null)} onSaved={() => { setEditing(null); refresh(); }} />}</div>;
}

function TaskRows({ tasks, empty }: { tasks: Task[]; empty: string }) { const refresh = () => window.location.hash = '#/tasks'; return <div className="task-list compact">{tasks.length ? tasks.map((task) => <TaskRow key={task.id} task={task} onComplete={async (id) => { await window.workbench.tasks.complete(id); refresh(); }} onEdit={() => window.location.hash = '#/tasks'} />) : <Empty text={empty} />}</div>; }
function TaskRow({ task, onComplete, onEdit }: { task: Task; onComplete: (id: string) => void; onEdit: (task: Task) => void }) { return <article className={`task-row ${task.status === 'done' ? 'is-done' : ''}`}><button className="check" onClick={() => task.status === 'done' ? onEdit(task) : onComplete(task.id)}>{task.status === 'done' ? '✓' : ''}</button><button className="task-main" onClick={() => onEdit(task)}><strong>{task.title}</strong><span>{task.projectName || '个人'} · {task.dueAt ? shortDate(task.dueAt) : '无截止日期'}</span></button><span className={`priority ${task.priority}`}>{priorityText[task.priority]}</span></article>; }
function Kanban({ tasks, refresh, edit }: { tasks: Task[]; refresh: () => void; edit: (task: Task) => void }) { return <div className="kanban">{(['todo', 'in_progress', 'done'] as TaskStatus[]).map((status) => <section className="kanban-column" key={status}><h3>{taskStatus[status]} <span>{tasks.filter((t) => t.status === status).length}</span></h3>{tasks.filter((t) => t.status === status).map((task) => <article className="kanban-card" key={task.id}><button onClick={() => edit(task)}><strong>{task.title}</strong><small>{task.dueAt ? shortDate(task.dueAt) : '未设置日期'}</small></button><div><button disabled={status === 'todo'} onClick={async () => { await window.workbench.tasks.move(task.id, status === 'done' ? 'in_progress' : 'todo'); refresh(); }}>←</button><button disabled={status === 'done'} onClick={async () => { await window.workbench.tasks.move(task.id, status === 'todo' ? 'in_progress' : 'done'); refresh(); }}>→</button></div></article>)}</section>)}</div>; }
function TaskDialog({ task, onClose, onSaved }: { task: Task | null; onClose: () => void; onSaved: () => void }) { const [title, setTitle] = useState(task?.title || ''); const [description, setDescription] = useState(task?.description || ''); const [priority, setPriority] = useState<TaskPriority>(task?.priority || 'medium'); const [status, setStatus] = useState<TaskStatus>(task?.status || 'todo'); const [repeatRule, setRepeat] = useState(task?.repeatRule || 'none'); const [due, setDue] = useState(task?.dueAt ? task.dueAt.slice(0, 16) : ''); const save = async (e: React.FormEvent) => { e.preventDefault(); await window.workbench.tasks.save({ id: task?.id, title, description, priority, status, repeatRule, dueAt: due ? new Date(due).toISOString() : null }); onSaved(); }; return <Dialog title={task ? '编辑任务' : '新建任务'} onClose={onClose}><form className="form-grid" onSubmit={save}><label className="wide">任务标题<input value={title} onChange={(e) => setTitle(e.target.value)} autoFocus required /></label><label className="wide">说明<textarea value={description} onChange={(e) => setDescription(e.target.value)} rows={4} /></label><label>状态<select value={status} onChange={(e) => setStatus(e.target.value as TaskStatus)}>{Object.entries(taskStatus).map(([v, n]) => <option value={v} key={v}>{n}</option>)}</select></label><label>优先级<select value={priority} onChange={(e) => setPriority(e.target.value as TaskPriority)}>{Object.entries(priorityText).map(([v, n]) => <option value={v} key={v}>{n}</option>)}</select></label><label>截止时间<input type="datetime-local" value={due} onChange={(e) => setDue(e.target.value)} /></label><label>重复<select value={repeatRule} onChange={(e) => setRepeat(e.target.value as any)}><option value="none">不重复</option><option value="daily">每天</option><option value="weekly">每周</option><option value="monthly">每月</option></select></label><div className="dialog-actions wide"><button className="quiet" type="button" onClick={onClose}>取消</button><button className="primary" type="submit">保存任务</button></div></form></Dialog>; }

function NotesPage() {
  const [notes, setNotes] = useState<Note[]>([]); const [selected, setSelected] = useState<Note | null>(null); const [search, setSearch] = useState(''); const [preview, setPreview] = useState(false);
  const refresh = () => window.workbench.notes.list(search).then((rows) => { setNotes(rows); if (selected) setSelected(rows.find((x) => x.id === selected.id) || null); });
  useEffect(() => { void refresh(); }, [search]);
  const create = () => { setPreview(false); setSelected({ id: '', title: '未命名笔记', content: '', projectId: null, tags: [], createdAt: '', updatedAt: '' }); };
  const save = async () => { if (!selected) return; const result = await window.workbench.notes.save({ id: selected.id || undefined, title: selected.title, content: selected.content }); setSelected(result); refresh(); };
  const attach = async () => { if (!selected?.id) return; const link = await window.workbench.notes.attach(selected.id); if (link) setSelected({ ...selected, content: `${selected.content}\n\n[附件](${link})` }); };
  const remove = async () => { if (!selected?.id || !window.confirm(`确定删除笔记“${selected.title}”吗？此操作无法恢复。`)) return; await window.workbench.notes.remove(selected.id); setSelected(null); refresh(); };
  return <div className="page notes-page"><aside className="notes-list"><div className="page-tools"><input className="search" placeholder="搜索笔记…" value={search} onChange={(e) => setSearch(e.target.value)} /><button className="primary icon-button" onClick={create}>＋</button></div>{notes.map((note) => <button className={`note-item ${selected?.id === note.id ? 'selected' : ''}`} key={note.id} onClick={() => { setPreview(false); setSelected(note); }}><strong>{note.title}</strong><small>{shortDate(note.updatedAt)} · {note.content.slice(0, 42) || '空白笔记'}</small></button>)}</aside><section className="editor-panel">{selected ? <><div className="editor-toolbar"><input className="note-title" value={selected.title} onChange={(e) => setSelected({ ...selected, title: e.target.value })} /><div><button className="quiet" onClick={() => setPreview(!preview)}>{preview ? '编辑' : '预览'}</button><button className="quiet" onClick={attach} disabled={!selected.id}>附件</button><button className="danger compact-danger" onClick={remove} disabled={!selected.id}>删除</button><button className="primary" onClick={save}>保存</button></div></div>{preview ? <article className="markdown-preview"><ReactMarkdown remarkPlugins={[remarkGfm]} rehypePlugins={[rehypeSanitize]}>{selected.content}</ReactMarkdown></article> : <CodeMirror value={selected.content} height="100%" theme={oneDark} extensions={[markdown()]} onChange={(content) => setSelected({ ...selected, content })} />}</> : <Empty text="选择一条笔记，或新建一条速记。" />}</section></div>;
}

function PromptsPage() {
  const [items, setItems] = useState<PromptTemplate[]>([]); const [selected, setSelected] = useState<PromptTemplate | null>(null); const [search, setSearch] = useState('');
  const refresh = () => window.workbench.prompts.list(search).then(setItems);
  useEffect(() => { void refresh(); }, [search]);
  const create = () => setSelected({ id: '', title: '未命名模板', body: '', categoryId: null, tags: [], favorite: false, usageCount: 0, lastUsedAt: null, createdAt: '', updatedAt: '' });
  const save = async () => { if (!selected) return; const value = await window.workbench.prompts.save({ id: selected.id || undefined, title: selected.title, body: selected.body, categoryId: selected.categoryId, favorite: selected.favorite }); setSelected(value); refresh(); };
  const use = async () => { if (!selected) return; const names = [...new Set([...selected.body.matchAll(/{{\s*([\w.-]+)\s*}}/g)].map((m) => m[1]))]; const values: Record<string, string> = {}; names.forEach((name) => { values[name] = window.prompt(`填写变量：${name}`, '') || ''; }); await window.workbench.prompts.use(selected.id, values); alert(names.length ? '已填充变量并复制到剪贴板。' : '模板已一键复制到剪贴板。'); refresh(); };
  const hasVariables = Boolean(selected && /{{\s*[\w.-]+\s*}}/.test(selected.body));
  return <div className="page prompts-page"><aside className="notes-list"><div className="page-tools"><input className="search" placeholder="搜索模板…" value={search} onChange={(e) => setSearch(e.target.value)} /><button className="primary icon-button" onClick={create}>＋</button></div>{items.map((item) => <button className={`note-item ${selected?.id === item.id ? 'selected' : ''}`} key={item.id} onClick={() => setSelected(item)}><strong>{item.favorite ? '★ ' : ''}{item.title}</strong><small>{item.categoryName || '未分类'} · 使用 {item.usageCount} 次</small></button>)}</aside><section className="editor-panel">{selected ? <><div className="editor-toolbar"><input className="note-title" value={selected.title} onChange={(e) => setSelected({ ...selected, title: e.target.value })} /><div><button className={`quiet ${selected.favorite ? 'starred' : ''}`} onClick={() => setSelected({ ...selected, favorite: !selected.favorite })}>★</button><button className="quiet" onClick={save}>保存</button><button className="primary" onClick={use} disabled={!selected.id}>{hasVariables ? '填充并复制' : '一键复制'}</button></div></div><CodeMirror value={selected.body} height="100%" theme={oneDark} extensions={[markdown()]} onChange={(body) => setSelected({ ...selected, body })} /><p className="hint">使用 <code>{'{{variable_name}}'}</code> 创建可填写变量。</p></> : <Empty text="选择模板，或新建一个可复用的提示词。" />}</section></div>;
}

function ReportsPage() { const [report, setReport] = useState<WeeklyReport | null>(null); const [message, setMessage] = useState(''); const refresh = () => window.workbench.reports.weekly().then(setReport); useEffect(() => { void refresh(); }, []); if (!report) return <Loading />; return <div className="page report"><div className="page-tools"><div><p className="muted">周一至周日 · 使用本机时区</p><h3>本周工作周报</h3></div><div><button className="quiet" onClick={async () => { await window.workbench.reports.copy(report.markdown); setMessage('已复制到剪贴板'); }}>复制 Markdown</button><button className="primary" onClick={async () => { const saved = await window.workbench.reports.saveWeekly(); if (saved) setMessage(`已保存至 ${saved}`); }}>导出 .md</button></div></div>{message && <p className="success">{message}</p>}<article className="markdown-preview report-content"><ReactMarkdown remarkPlugins={[remarkGfm]} rehypePlugins={[rehypeSanitize]}>{report.markdown}</ReactMarkdown></article></div>; }

function SettingsPage() { const [message, setMessage] = useState(''); return <div className="page settings"><section className="settings-card"><h3>本地备份与恢复</h3><p>备份包含加密数据库、密钥信封与附件。恢复后将使用该备份原有的主密码。</p><div><button className="primary" onClick={async () => { const file = await window.workbench.backup.export(); if (file) setMessage(`已导出：${file}`); }}>导出加密备份</button><button className="danger" onClick={() => void window.workbench.backup.restore()}>从备份恢复</button></div></section><section className="settings-card warning"><h3>卸载数据策略</h3><p>卸载“Zzz 的工作站”时，将永久删除本机应用目录中的数据库、附件、缓存、设置及应用内备份。手动导出至其他位置的备份不会被删除。</p></section>{message && <p className="success">{message}</p>}</div>; }

function Metric({ label, value, tone }: { label: string; value: number; tone: string }) { return <article className={`metric ${tone}`}><span>{label}</span><strong>{value}</strong></article>; }
function Panel({ title, action, onAction, children }: { title: string; action?: string; onAction?: () => void; children: React.ReactNode }) { return <section className="panel"><header><h3>{title}</h3>{action && <button className="link-button" onClick={onAction}>{action} →</button>}</header>{children}</section>; }
function Loading() { return <div className="loading">正在打开加密工作站…</div>; }
export default function App() { return <HashRouter><AuthGate /></HashRouter>; }
